#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER ${DB_USER_MC} WITH PASSWORD '${DB_PASSWORD_MC}';

    GRANT CONNECT ON DATABASE ${POSTGRES_DB} TO ${DB_USER_MC};
    GRANT ALL PRIVILEGES ON DATABASE ${POSTGRES_DB} TO ${DB_USER_MC};
EOSQL
